package rules;

import com.arz.linkme.analytics.model.Order

rule "HDFC"

when
orderObject: Order(cardType=="HDFC" && price>10000);
then
orderObject.setDiscount(10);
end;

rule "SAAB"

when
orderObject: Order(cardType=="SAAB" && price>15000);
then
orderObject.setDiscount(10);
end;

rule "SAMBA"

when
orderObject: Order(cardType=="SAMBA" && price>10000);
then
orderObject.setDiscount(5);
end;